# Summer Analytics 2022 - Basic Data Analysis

- ####  Welcome to your first assignment, on basic data analysis!
- #### This Assignment is ungraded



### 1) Import Pandas

In [ ]:
#your code here
import pandas as pd

### 2) Import the dataset and  Assign it to a variable called users and use the 'user_id' as index

Use the following dataset
https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user

In [ ]:
#your code here
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
user_data = pd.read_csv(url,delimiter = '|')
user_data.set_index("user_id" , inplace=True)
user_data

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### 3) Display the first 25 entries

In [ ]:
#your code here
user_data.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### 4) Display the last 10 entries

In [ ]:
#your code here
user_data.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### 5) What is the number of observations in the dataset?

In [ ]:
#your code here
user_data.shape[0]
#there are 943 obserdations , and each observation haveing 4 entries .

943

### 6) What is the number of columns in the dataset, also print the name of all the columns?

In [ ]:
#your code here
print(user_data.shape[1])
print(user_data.columns)

4
Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### 7) What is the data type of each column?

In [ ]:
#your code here
user_data.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### 8) Print only the occupation column

In [ ]:
#your code here
user_data['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### 9) How many different occupations are in this dataset?

In [ ]:
#your code here
user_data['occupation'].nunique()

21

### 10) What is the most frequent occupation?

In [ ]:
#your code here
user_data['occupation'].value_counts().idxmax()
#hence most frequent occupation is student

'student'

### 11) Summarize the DataFrame.

In [ ]:
#your code here
user_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

### 12) Summarize only the occupation column

In [ ]:
#your code here
user_data['occupation'].info()

<class 'pandas.core.series.Series'>
Index: 943 entries, 1 to 943
Series name: occupation
Non-Null Count  Dtype
--------------  -----
943 non-null    object
dtypes: object(1)
memory usage: 14.7+ KB

### 13) What is the mean age of users?

In [ ]:
#your code here
user_data['age'].mean()

34.05196182396607

### 14) What is the age with least occurrence?

In [ ]:
frequency = user_data['age'].value_counts()
min = frequency.min()

least = frequency[frequency == min]

for i in least.index:
  print(i)

7
66
11
10
73